<?
$module=7;
// index.php
include($_SERVER['DOCUMENT_ROOT']."/includes/initiate.php");

if (!$mod) {

	$mod = "event";
} 

if ($mod == "album") {

	$date_type = "release_date";
	$order_fill = "release_date desc";
	
} elseif ($mod == "event") {

	$date_type = "bdate";
	$current_fill = "and e.bdate >= now()";
	$order_fill = "bdate";
	
}

$events = sql_query("select  smap.id, 
									 e.".$date_type." as date,
									 e.title,
									 s.*,
									 smap.ideas									 
								from streetteam_".$mod."_map as smap,
									 ".$mod."s as e,
									 streetteam as s
							   where smap.".$mod."_id = e.id
							     and smap.member_id = s.id
								     $current_fill
						        order by $order_fill, s.lname");

$filename = ucwords($mod)."_Street_Team_List_(". date("Y-m-d") . ").xls";		

header("Content-type: application/vnd.ms-excel"); 
header("Content-disposition: attachment; filename=$filename"); 
header("Pragma: no-cache"); 
header("Expires: 0"); 

?>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="csv_files/filelist.xml">
<style id="Event_Street_Team_List_(2005-08-05)-2_29386_Styles">
<!--
table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:1.0in .75in 1.0in .75in;
	mso-header-margin:.5in;
	mso-footer-margin:.5in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.normal
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:top;
	border:none;
	white-space:nowrap;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	}
.ideas
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:top;
	border:none;
	white-space:normal;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	}
.date
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:"Short Date";
	text-align:general;
	vertical-align:top;
	border:none;
	white-space:nowrap;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>Sheet1</x:Name>
    <x:WorksheetOptions>
     <x:CodeName>Sheet1</x:CodeName>
     <x:Selected/>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>15465</x:WindowHeight>
  <x:WindowWidth>18060</x:WindowWidth>
  <x:WindowTopX>480</x:WindowTopX>
  <x:WindowTopY>60</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
</xml><![endif]-->
</head>
<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel's Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->
<div id="Event_Street_Team_List_(2005-08-05)-2_29386" align=center x:publishsource="Excel">
  <table x:str border=0 cellpadding=0 cellspacing=0 width=2016 class=normal style='border-collapse:collapse;table-layout:fixed;width:1514pt'>
    <col class=normal width=21 style='mso-width-source:userset;mso-width-alt: 768;width:16pt'>
    <col class=normal width=71 style='mso-width-source:userset;mso-width-alt: 2596;width:53pt'>
    <col class=normal width=107 style='mso-width-source:userset;mso-width-alt: 3913;width:80pt'>
    <col class=normal width=62 style='mso-width-source:userset;mso-width-alt: 2267;width:47pt'>
    <col class=normal width=67 style='mso-width-source:userset;mso-width-alt: 2450;width:50pt'>
    <col class=normal width=200 style='mso-width-source:userset;mso-width-alt: 7314;width:150pt'>
    <col class=normal width=122 style='mso-width-source:userset;mso-width-alt: 4461;width:92pt'>
    <col class=normal width=90 style='mso-width-source:userset;mso-width-alt: 3291;width:68pt'>
    <col class=normal width=93 style='mso-width-source:userset;mso-width-alt: 3401;width:70pt'>
    <col class=normal width=74 style='mso-width-source:userset;mso-width-alt: 2706;width:56pt'>
    <col class=normal width=94 style='mso-width-source:userset;mso-width-alt: 3437;width:71pt'>
    <col class=normal width=97 style='mso-width-source:userset;mso-width-alt: 3547;width:73pt'>
    <col class=normal width=208 style='mso-width-source:userset;mso-width-alt: 7606;width:156pt'>
    <col class=normal width=355 style='mso-width-source:userset;mso-width-alt: 12982;width:266pt'>
    <col class=xl2329386 width=355 style='mso-width-source:userset;mso-width-alt: 12982;width:266pt'>
    <tr height=17 style='height:12.75pt'>
      <td height=17 class=normal width=21 style='height:12.75pt;width:16pt'>id</td>
      <td class=normal width=71 style='width:53pt'>date</td>
      <td class=normal width=107 style='width:80pt'>event</td>
      <td class=normal width=62 style='width:47pt'>firstname</td>
      <td class=normal width=67 style='width:50pt'>lastname</td>
      <td class=normal width=200 style='width:150pt'>address1</td>
      <td class=normal width=122 style='width:92pt'>address2</td>
      <td class=normal width=90 style='width:68pt'>city</td>
      <td class=normal width=93 style='width:70pt'>state</td>
      <td class=normal width=74 style='width:56pt'>zip</td>
      <td class=normal width=94 style='width:71pt'>phone</td>
      <td class=normal width=97 style='width:73pt'>fax</td>
      <td class=normal width=208 style='width:156pt'>email</td>
      <td class=normal width=355 style='width:266pt'>schoolbiz</td>
      <td class=ideas width=355 style='width:266pt'>ideas</td>
    </tr>

<?

$num = count($events);

for ($i=0; $i<$num; $i++) { 
	 echo "<tr height=85 style='height:63.75pt'>
      <td height=85 class=normal align=right style='height:63.75pt' x:num>".$events[$i]['id']."</td>
      <td class=date>".$events[$i]['date']."</td>
      <td class=normal>".$events[$i]['title']."</td>
      <td class=normal>".$events[$i]['fname']."</td>
      <td class=normal>".$events[$i]['lname']."</td>
      <td class=normal>".$events[$i]['address1']."</td>
      <td class=normal>".$events[$i]['address2']."</td>
      <td class=normal>".$events[$i]['city']."</td>
      <td class=normal>".$events[$i]['state']."</td>
      <td class=normal align=right x:num>".$events[$i]['zip']."</td>
      <td class=normal>".$events[$i]['phone']."</td>
      <td class=normal>".$events[$i]['fax']."</td>
      <td class=normal>".$events[$i]['email']."</td>
      <td class=normal>".$events[$i]['school']."</td>
      <td class=ideas width=355 style='width:266pt'>".str_replace("\r"," ",str_replace("\n"," ",$events[$i]['ideas']))."</td>
    </tr>";
}

mysql_close();
?>
    <![if supportMisalignedColumns]>
    <tr height=0 style='display:none'>
      <td width=21 style='width:16pt'></td>
      <td width=71 style='width:53pt'></td>
      <td width=107 style='width:80pt'></td>
      <td width=62 style='width:47pt'></td>
      <td width=67 style='width:50pt'></td>
      <td width=200 style='width:150pt'></td>
      <td width=122 style='width:92pt'></td>
      <td width=90 style='width:68pt'></td>
      <td width=93 style='width:70pt'></td>
      <td width=74 style='width:56pt'></td>
      <td width=94 style='width:71pt'></td>
      <td width=97 style='width:73pt'></td>
      <td width=208 style='width:156pt'></td>
      <td width=355 style='width:266pt'></td>
      <td width=355 style='width:266pt'></td>
    </tr>
    <![endif]>
  </table>
</div>
<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>
</html>
